apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB: "mongodb://{{ .Values.global.mongodb.reports.user }}:{{ .Values.global.mongodb.reports.password }}@mongodb:{{ .Values.global.mongodb.containerPort }}/{{ .Values.global.mongodb.reports.database }}"